name: Docker pipeline workflow
on:
  workflow_dispatch:
  
  schedule:
    # build every Sunday
    - cron:  '* * * * 0'    
  
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "make version"
        run: make version
      - name: "make push"
        run: make push
        env: 
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
